name: Unittests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.12"
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        environment-file: environment.yml
        use-mamba: true
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 5
      run: |
        pip install .
        papermill lammps_dataclass.ipynb lammps_dataclass_out.ipynb -k python3
        papermill sphinxdft_dataclass.ipynb sphinxdft_dataclass_out.ipynb -k python3
